# Generated by Django 4.1.4 on 2022-12-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='circuitos')),
                ('vuelta_rapida', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('numero_de_vueltas', models.CharField(max_length=50)),
                ('fecha_de_apertura', models.CharField(max_length=50)),
                ('numero_de_curvas', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
            },
        ),
    ]
