# Generated by Django 4.1.4 on 2022-12-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('escuderia', models.CharField(max_length=50)),
                ('victorias', models.IntegerField()),
                ('podios', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'piloto',
                'verbose_name_plural': 'pilotos',
            },
        ),
    ]
