# Generated by Django 4.1.4 on 2022-12-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='imagen',
            field=models.ImageField(upload_to='pilotos'),
        ),
    ]
